package com.itextpdf.text.xml.simpleparser;

import androidx.exifinterface.media.ExifInterface;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.html.HtmlTags;
import com.itextpdf.text.pdf.Barcode128;
import com.itextpdf.text.xml.xmp.PdfProperties;
import java.util.HashMap;
import java.util.Map;
import kotlin.text.Typography;

public class EntitiesToSymbol {
    private static final Map<String, Character> MAP;

    static {
        HashMap hashMap = new HashMap();
        MAP = hashMap;
        hashMap.put("169", 227);
        hashMap.put("172", 216);
        hashMap.put("174", 210);
        Character valueOf = Character.valueOf(Typography.plusMinus);
        hashMap.put("177", valueOf);
        hashMap.put("215", 180);
        hashMap.put("247", 184);
        hashMap.put("8230", 188);
        Character valueOf2 = Character.valueOf(Typography.cent);
        hashMap.put("8242", valueOf2);
        hashMap.put("8243", 178);
        hashMap.put("8260", 164);
        hashMap.put("8364", 240);
        hashMap.put("8465", 193);
        Character valueOf3 = Character.valueOf(Barcode128.DEL);
        hashMap.put("8472", valueOf3);
        hashMap.put("8476", 194);
        hashMap.put("8482", 212);
        hashMap.put("8501", 192);
        hashMap.put("8592", 172);
        hashMap.put("8593", 173);
        hashMap.put("8594", Character.valueOf(Typography.registered));
        hashMap.put("8595", 175);
        hashMap.put("8596", 171);
        hashMap.put("8629", 191);
        hashMap.put("8656", 220);
        hashMap.put("8657", 221);
        hashMap.put("8658", 222);
        hashMap.put("8659", 223);
        hashMap.put("8660", 219);
        hashMap.put("8704", Character.valueOf(Typography.quote));
        hashMap.put("8706", Character.valueOf(Typography.paragraph));
        hashMap.put("8707", Character.valueOf(Typography.dollar));
        hashMap.put("8709", Character.valueOf(Barcode128.SHIFT));
        hashMap.put("8711", 209);
        hashMap.put("8712", 206);
        hashMap.put("8713", 207);
        hashMap.put("8717", '\'');
        hashMap.put("8719", 213);
        hashMap.put("8721", 229);
        hashMap.put("8722", '-');
        hashMap.put("8727", '*');
        hashMap.put("8729", Character.valueOf(Typography.middleDot));
        hashMap.put("8730", 214);
        hashMap.put("8733", 181);
        hashMap.put("8734", 165);
        hashMap.put("8736", 208);
        hashMap.put("8743", 217);
        hashMap.put("8744", 218);
        hashMap.put("8745", Character.valueOf(Barcode128.CODE_C));
        hashMap.put("8746", 200);
        hashMap.put("8747", 242);
        hashMap.put("8756", '\\');
        hashMap.put("8764", '~');
        hashMap.put("8773", '@');
        hashMap.put("8776", 187);
        hashMap.put("8800", 185);
        hashMap.put("8801", 186);
        hashMap.put("8804", Character.valueOf(Typography.pound));
        hashMap.put("8805", 179);
        hashMap.put("8834", Character.valueOf(Barcode128.STARTB));
        hashMap.put("8835", 201);
        hashMap.put("8836", Character.valueOf(Barcode128.STARTA));
        hashMap.put("8838", Character.valueOf(Barcode128.STARTC));
        hashMap.put("8839", Character.valueOf(Barcode128.FNC1));
        hashMap.put("8853", Character.valueOf(Barcode128.FNC2));
        hashMap.put("8855", Character.valueOf(Barcode128.FNC3));
        hashMap.put("8869", '^');
        hashMap.put("8901", Character.valueOf(Typography.times));
        hashMap.put("8992", 243);
        hashMap.put("8993", 245);
        hashMap.put("9001", 225);
        hashMap.put("9002", 241);
        hashMap.put("913", 'A');
        hashMap.put("914", 'B');
        hashMap.put("915", 'G');
        hashMap.put("916", 'D');
        hashMap.put("917", 'E');
        hashMap.put("918", 'Z');
        hashMap.put("919", 'H');
        hashMap.put("920", 'Q');
        hashMap.put("921", 'I');
        hashMap.put("922", 'K');
        hashMap.put("923", 'L');
        hashMap.put("924", 'M');
        hashMap.put("925", 'N');
        hashMap.put("926", 'X');
        hashMap.put("927", 'O');
        hashMap.put("928", 'P');
        hashMap.put("929", 'R');
        hashMap.put("931", 'S');
        hashMap.put("932", 'T');
        hashMap.put("933", 'U');
        hashMap.put("934", 'F');
        hashMap.put("935", 'C');
        hashMap.put("936", 'Y');
        hashMap.put("937", 'W');
        hashMap.put("945", 'a');
        hashMap.put("946", 'b');
        hashMap.put("947", Character.valueOf(Barcode128.START_A));
        hashMap.put("948", Character.valueOf(Barcode128.CODE_AC_TO_B));
        hashMap.put("949", Character.valueOf(Barcode128.CODE_BC_TO_A));
        hashMap.put("950", 'z');
        hashMap.put("951", Character.valueOf(Barcode128.START_B));
        hashMap.put("952", 'q');
        hashMap.put("953", Character.valueOf(Barcode128.START_C));
        hashMap.put("954", 'k');
        hashMap.put("955", 'l');
        hashMap.put("956", 'm');
        hashMap.put("957", 'n');
        hashMap.put("958", 'x');
        hashMap.put("959", 'o');
        hashMap.put("960", 'p');
        hashMap.put("961", 'r');
        hashMap.put("962", 'V');
        hashMap.put("963", 's');
        hashMap.put("964", 't');
        hashMap.put("965", 'u');
        hashMap.put("966", Character.valueOf(Barcode128.FNC1_INDEX));
        hashMap.put("967", Character.valueOf(Barcode128.CODE_AB_TO_C));
        hashMap.put("9674", 224);
        hashMap.put("968", 'y');
        hashMap.put("969", 'w');
        hashMap.put("977", 'J');
        hashMap.put("978", 161);
        hashMap.put("981", 'j');
        hashMap.put("982", 'v');
        hashMap.put("9824", 170);
        hashMap.put("9827", Character.valueOf(Typography.section));
        hashMap.put("9829", Character.valueOf(Typography.copyright));
        hashMap.put("9830", 168);
        hashMap.put("Alpha", 'A');
        hashMap.put("Beta", 'B');
        hashMap.put("Chi", 'C');
        hashMap.put("Delta", 'D');
        hashMap.put("Epsilon", 'E');
        hashMap.put("Eta", 'H');
        hashMap.put(ExifInterface.TAG_GAMMA, 'G');
        hashMap.put("Iota", 'I');
        hashMap.put("Kappa", 'K');
        hashMap.put("Lambda", 'L');
        hashMap.put("Mu", 'M');
        hashMap.put("Nu", 'N');
        hashMap.put("Omega", 'W');
        hashMap.put("Omicron", 'O');
        hashMap.put("Phi", 'F');
        hashMap.put("Pi", 'P');
        hashMap.put("Prime", 178);
        hashMap.put("Psi", 'Y');
        hashMap.put("Rho", 'R');
        hashMap.put("Sigma", 'S');
        hashMap.put("Tau", 'T');
        hashMap.put("Theta", 'Q');
        hashMap.put("Upsilon", 'U');
        hashMap.put("Xi", 'X');
        hashMap.put("Zeta", 'Z');
        hashMap.put("alefsym", 192);
        hashMap.put("alpha", 'a');
        hashMap.put("and", 217);
        hashMap.put("ang", 208);
        hashMap.put("asymp", 187);
        hashMap.put("beta", 'b');
        hashMap.put("cap", Character.valueOf(Barcode128.CODE_C));
        hashMap.put("chi", Character.valueOf(Barcode128.CODE_AB_TO_C));
        hashMap.put("clubs", Character.valueOf(Typography.section));
        hashMap.put("cong", '@');
        hashMap.put("copy", 211);
        hashMap.put("crarr", 191);
        hashMap.put("cup", 200);
        hashMap.put("dArr", 223);
        hashMap.put("darr", 175);
        hashMap.put("delta", Character.valueOf(Barcode128.CODE_AC_TO_B));
        hashMap.put("diams", 168);
        hashMap.put("divide", 184);
        hashMap.put("empty", Character.valueOf(Barcode128.SHIFT));
        hashMap.put("epsilon", Character.valueOf(Barcode128.CODE_BC_TO_A));
        hashMap.put("equiv", 186);
        hashMap.put("eta", Character.valueOf(Barcode128.START_B));
        hashMap.put("euro", 240);
        hashMap.put("exist", Character.valueOf(Typography.dollar));
        hashMap.put("forall", Character.valueOf(Typography.quote));
        hashMap.put("frasl", 164);
        hashMap.put("gamma", Character.valueOf(Barcode128.START_A));
        hashMap.put("ge", 179);
        hashMap.put("hArr", 219);
        hashMap.put("harr", 171);
        hashMap.put("hearts", Character.valueOf(Typography.copyright));
        hashMap.put("hellip", 188);
        hashMap.put("horizontal arrow extender", 190);
        hashMap.put("image", 193);
        hashMap.put("infin", 165);
        hashMap.put("int", 242);
        hashMap.put("iota", Character.valueOf(Barcode128.START_C));
        hashMap.put("isin", 206);
        hashMap.put("kappa", 'k');
        hashMap.put("lArr", 220);
        hashMap.put("lambda", 'l');
        hashMap.put("lang", 225);
        hashMap.put("large brace extender", 239);
        hashMap.put("large integral extender", 244);
        hashMap.put("large left brace (bottom)", 238);
        hashMap.put("large left brace (middle)", 237);
        hashMap.put("large left brace (top)", 236);
        hashMap.put("large left bracket (bottom)", 235);
        hashMap.put("large left bracket (extender)", 234);
        hashMap.put("large left bracket (top)", 233);
        hashMap.put("large left parenthesis (bottom)", 232);
        hashMap.put("large left parenthesis (extender)", 231);
        hashMap.put("large left parenthesis (top)", 230);
        hashMap.put("large right brace (bottom)", 254);
        hashMap.put("large right brace (middle)", 253);
        hashMap.put("large right brace (top)", 252);
        hashMap.put("large right bracket (bottom)", 251);
        hashMap.put("large right bracket (extender)", 250);
        hashMap.put("large right bracket (top)", 249);
        hashMap.put("large right parenthesis (bottom)", 248);
        hashMap.put("large right parenthesis (extender)", 247);
        hashMap.put("large right parenthesis (top)", 246);
        hashMap.put("larr", 172);
        hashMap.put("le", Character.valueOf(Typography.pound));
        hashMap.put("lowast", '*');
        hashMap.put("loz", 224);
        hashMap.put("minus", '-');
        hashMap.put("mu", 'm');
        hashMap.put("nabla", 209);
        hashMap.put("ne", 185);
        hashMap.put("not", 216);
        hashMap.put("notin", 207);
        hashMap.put("nsub", Character.valueOf(Barcode128.STARTA));
        hashMap.put("nu", 'n');
        hashMap.put("omega", 'w');
        hashMap.put("omicron", 'o');
        hashMap.put("oplus", Character.valueOf(Barcode128.FNC2));
        hashMap.put("or", 218);
        hashMap.put("otimes", Character.valueOf(Barcode128.FNC3));
        hashMap.put(PdfProperties.PART, Character.valueOf(Typography.paragraph));
        hashMap.put("perp", '^');
        hashMap.put("phi", Character.valueOf(Barcode128.FNC1_INDEX));
        hashMap.put("pi", 'p');
        hashMap.put("piv", 'v');
        hashMap.put("plusmn", valueOf);
        hashMap.put("prime", valueOf2);
        hashMap.put("prod", 213);
        hashMap.put("prop", 181);
        hashMap.put("psi", 'y');
        hashMap.put("rArr", 222);
        hashMap.put("radic", 214);
        hashMap.put("radical extender", '`');
        hashMap.put("rang", 241);
        hashMap.put("rarr", Character.valueOf(Typography.registered));
        hashMap.put("real", 194);
        hashMap.put("reg", 210);
        hashMap.put("rho", 'r');
        hashMap.put("sdot", Character.valueOf(Typography.times));
        hashMap.put("sigma", 's');
        hashMap.put("sigmaf", 'V');
        hashMap.put("sim", '~');
        hashMap.put("spades", 170);
        hashMap.put("sub", Character.valueOf(Barcode128.STARTB));
        hashMap.put("sube", Character.valueOf(Barcode128.STARTC));
        hashMap.put("sum", 229);
        hashMap.put(HtmlTags.SUP, 201);
        hashMap.put("supe", Character.valueOf(Barcode128.FNC1));
        hashMap.put("tau", 't');
        hashMap.put("there4", '\\');
        hashMap.put("theta", 'q');
        hashMap.put("thetasym", 'J');
        hashMap.put("times", 180);
        hashMap.put("trade", 212);
        hashMap.put("uArr", 221);
        hashMap.put("uarr", 173);
        hashMap.put("upsih", 161);
        hashMap.put("upsilon", 'u');
        hashMap.put("vertical arrow extender", Character.valueOf(Typography.half));
        hashMap.put("weierp", valueOf3);
        hashMap.put("xi", 'x');
        hashMap.put("zeta", 'z');
    }

    public static Chunk get(String str, Font font) {
        char correspondingSymbol = getCorrespondingSymbol(str);
        if (correspondingSymbol == 0) {
            try {
                return new Chunk(String.valueOf((char) Integer.parseInt(str)), font);
            } catch (Exception unused) {
                return new Chunk(str, font);
            }
        } else {
            return new Chunk(String.valueOf(correspondingSymbol), new Font(Font.FontFamily.SYMBOL, font.getSize(), font.getStyle(), font.getColor()));
        }
    }

    public static char getCorrespondingSymbol(String str) {
        Character ch = MAP.get(str);
        if (ch == null) {
            return 0;
        }
        return ch.charValue();
    }
}
