package com.mintti.visionsdk.ble.bean;

public enum BgEvent {
    BG_EVENT_CALIBRATION_FAILED,
    BG_EVENT_WAIT_PAGER_INSERT,
    BG_EVENT_WAIT_DRIP_BLOOD,
    BG_EVENT_BLOOD_SAMPLE_DETECTING,
    BG_EVENT_GET_BG_RESULT_TIMEOUT,
    BG_EVENT_MEASURE_END,
    BG_EVENT_PAPER_USED
}
